spring:
  datasource:
    url: jdbc:h2:mem:testdb   # H2 ??? ?????? URL
    driver-class-name: org.h2.Driver
    username: sa              # ??? ??
    password:
  h2:
    console:
      enabled: true           # H2 ?? ???
  jpa:
    hibernate:
      ddl-auto: update        # Hibernate DDL ?? ?? ??
    show-sql: true            # SQL ?? ???